# Generated by Django 2.0.13 on 2019-09-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='outlined_material_icon_name',
            field=models.CharField(default='message', max_length=200),
            preserve_default=False,
        ),
    ]
