# Generated by Django 2.0.13 on 2019-09-12 22:02

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190912_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
